// <auto-generated />
using System;
using Glossary.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Glossary.Infrastructure.Migrations
{
    [DbContext(typeof(GlossaryDbContext))]
    [Migration("20200609040939_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Glossary.Core.Models.Glossary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Glossary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("705b3587-eec0-434e-90ae-7e0a3d3326e3"),
                            Definition = "The ocean floor offshore from the continental margin, usually very flat with a slight slope.",
                            Term = "abyssal plain"
                        },
                        new
                        {
                            Id = new Guid("ebffa4ff-727c-4736-a316-0ae006b1c8c7"),
                            Definition = "To add terranes (small land masses or pieces of crust) to another, usually larger, land mass.",
                            Term = "accrete"
                        },
                        new
                        {
                            Id = new Guid("f623e3a8-3858-4336-a5c5-bb397013b75d"),
                            Definition = "Term pertaining to a highly basic, as opposed to acidic, subtance. For example, hydroxide or carbonate of sodium or potassium.",
                            Term = "alkaline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
